const COUNTRY_CODES: Record<string, string> = {
  Argentina: 'ar',
  Argelia: 'dz',
  Australia: 'au',
  Austria: 'at',
  'Arabia Saudita': 'sa',
  'Arabia Saudí': 'sa',
  Alemania: 'de',
  Belgica: 'be',
  Bélgica: 'be',
  'Bosnia y Herzegovina': 'ba',
  Brasil: 'br',
  'Cabo Verde': 'cv',
  Camerun: 'cm',
  Camerún: 'cm',
  Canada: 'ca',
  Canadá: 'ca',
  Catar: 'qa',
  Qatar: 'qa',
  Colombia: 'co',
  'Corea del Sur': 'kr',
  'Costa de Marfil': 'ci',
  Croacia: 'hr',
  Curazao: 'cw',
  Dinamarca: 'dk',
  Ecuador: 'ec',
  Egipto: 'eg',
  Escocia: 'gb-sct',
  Espana: 'es',
  España: 'es',
  'Estados Unidos': 'us',
  Francia: 'fr',
  Ghana: 'gh',
  Haiti: 'ht',
  Haití: 'ht',
  Hungria: 'hu',
  Hungría: 'hu',
  Inglaterra: 'gb-eng',
  Iran: 'ir',
  Irán: 'ir',
  Irak: 'iq',
  Iraq: 'iq',
  Italia: 'it',
  Japon: 'jp',
  Japón: 'jp',
  Jordania: 'jo',
  Mali: 'ml',
  Malí: 'ml',
  Marruecos: 'ma',
  Mexico: 'mx',
  México: 'mx',
  Nigeria: 'ng',
  Noruega: 'no',
  'Nueva Zelanda': 'nz',
  'Paises Bajos': 'nl',
  'Países Bajos': 'nl',
  Panama: 'pa',
  Panamá: 'pa',
  Paraguay: 'py',
  Polonia: 'pl',
  Portugal: 'pt',
  'RD Congo': 'cd',
  'Republica Checa': 'cz',
  'República Checa': 'cz',
  Senegal: 'sn',
  Serbia: 'rs',
  Sudafrica: 'za',
  Sudáfrica: 'za',
  Suecia: 'se',
  Suiza: 'ch',
  Tunez: 'tn',
  Túnez: 'tn',
  Turquia: 'tr',
  Turquía: 'tr',
  Ucrania: 'ua',
  Uruguay: 'uy',
  Uzbekistán: 'uz',
  Uzbekistan: 'uz',
};

export function getFlagUrl(pais: string): string {
  const code = COUNTRY_CODES[pais];
  if (!code) return '';
  return `https://flagcdn.com/w20/${code}.png`;
}

export function getFlagSrcset(pais: string): string {
  const code = COUNTRY_CODES[pais];
  if (!code) return '';
  return `https://flagcdn.com/w40/${code}.png 2x`;
}
